// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNUwvSvuBhlf28rR8gZePndgbBxZ-_pFU',
    appId: '1:779062347093:web:3c213c785fda7870fe5bdc',
    messagingSenderId: '779062347093',
    projectId: 'fir-auth-895ed',
    authDomain: 'fir-auth-895ed.firebaseapp.com',
    storageBucket: 'fir-auth-895ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtMIobP-uxbWJFqX9LHDjBBh-9i2gA4O0',
    appId: '1:779062347093:android:90e6530796940d77fe5bdc',
    messagingSenderId: '779062347093',
    projectId: 'fir-auth-895ed',
    storageBucket: 'fir-auth-895ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf_Eu790D7xCA8yp1asB_vI4Si-cy0ERE',
    appId: '1:779062347093:ios:9ecd9b27faf5286ffe5bdc',
    messagingSenderId: '779062347093',
    projectId: 'fir-auth-895ed',
    storageBucket: 'fir-auth-895ed.firebasestorage.app',
    iosBundleId: 'com.example.firebaseBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf_Eu790D7xCA8yp1asB_vI4Si-cy0ERE',
    appId: '1:779062347093:ios:9ecd9b27faf5286ffe5bdc',
    messagingSenderId: '779062347093',
    projectId: 'fir-auth-895ed',
    storageBucket: 'fir-auth-895ed.firebasestorage.app',
    iosBundleId: 'com.example.firebaseBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNUwvSvuBhlf28rR8gZePndgbBxZ-_pFU',
    appId: '1:779062347093:web:1ae6d17867d40b22fe5bdc',
    messagingSenderId: '779062347093',
    projectId: 'fir-auth-895ed',
    authDomain: 'fir-auth-895ed.firebaseapp.com',
    storageBucket: 'fir-auth-895ed.firebasestorage.app',
  );
}
